Repository paritytech/Nomidot, pull requests merged in 2019-11, with the labels that each got.

#12 Onboard with Extension
  front/context/src/AccountsContext.tsx
  front/context/src/ApiContext.tsx
  front/context/src/StakingContext.tsx
  front/context/src/index.ts
  front/context/src/types.ts
  front/gatsby/gatsby-config.js
  front/gatsby/package.json
  front/gatsby/src/ContextGate.tsx
  front/gatsby/src/components/header.tsx
  front/gatsby/src/components/image.tsx
  front/gatsby/src/components/layout.tsx
  front/gatsby/src/components/seo.tsx
  front/gatsby/src/pages/404.tsx
  front/gatsby/src/pages/home.tsx
  front/gatsby/src/pages/index.tsx
  front/gatsby/src/pages/onboarding.tsx
  front/ui-components/package.json
  front/ui-components/src/AccountsList.tsx
  front/ui-components/src/BalanceDisplay.tsx
  front/ui-components/src/Breadcrumbs.tsx
  front/ui-components/src/Circle.tsx
  front/ui-components/src/Modal.tsx
  front/ui-components/src/NavHeader.tsx
  front/ui-components/src/Shared.styles.ts
  front/ui-components/src/globalStyle.ts
  front/ui-components/src/index.ts
  front/ui-components/src/stateful/AddressSummary/AddressSummary.tsx
  front/ui-components/src/stateful/Balance.tsx
  front/ui-components/stories/Header.stories.tsx
  front/ui-components/stories/Modal.stories.tsx
  yarn.lock
Labels: A3-inprogress

#15 chore: remove eslint-config-react-app
  front/gatsby/src/pages/onboarding.tsx
  package.json
  yarn.lock
Labels: A0-pleasereview, A2-insubstantial

#18 feat: clean build and cache script
  package.json
  scripts/clean-build.sh
Labels: A0-pleasereview, A2-insubstantial

#19 refactor: Move ContextGate logic into ApiContext
  front/context/src/AccountsContext.tsx
  front/context/src/ApiContext.tsx
  front/gatsby/src/ContextGate.tsx
  front/ui-components/src/index.ts
Labels: A8-looksgood

#22 fix: Add forgotten Dropdown in ui-components
  front/ui-components/src/index.ts
Labels: A0-pleasereview, A2-insubstantial

#23 fix: Fix various little bugs
  front/context/src/types.ts
  front/context/src/util/isTestChain.ts
  front/context/src/util/keyring.ts
  front/context/src/util/validate.ts
  front/ui-components/src/Dropdown.ts
  front/ui-components/src/Shared.styles.ts
  front/ui-components/src/constants.ts
  front/ui-components/src/globalStyle.ts
  front/ui-components/src/index.ts
  front/ui-components/src/types.ts
  front/ui-components/src/util/toAddress.ts
  front/ui-components/src/util/toShortAddress.ts
  front/ui-components/stories/customDecorators/index.ts
  package.json
  scripts/clean-build.sh
  tsconfig.json
Labels: A0-pleasereview

#26 fix: Allow importing without src/ directory
  front/gatsby/gatsby-node.js
  front/gatsby/src/ContextGate.tsx
  front/gatsby/src/components/layout.tsx
  front/gatsby/src/pages/home.tsx
  front/gatsby/src/pages/index.tsx
  front/gatsby/src/pages/onboarding.tsx
  front/gatsby/tsconfig.json
  front/ui-components/src/AccountsList.tsx
  front/ui-components/src/stateful/Balance.tsx
  tsconfig.json
Labels: A0-pleasereview
