Repository paritytech/Nomidot, pull requests merged in 2020-02, with the labels that each got.

#127 chore: new image
  back/node_watcher/kubernetes/nomidotwatcher-job.yaml
Labels: A2-insubstantial

#137 Fix: #126 fix: #125
  back/node_watcher/src/tasks/createProposalStatus.ts
Labels: A0-pleasereview

#136 feat(gatsby): Inject accounts into header
  README.md
  front/Dockerfile
  front/context/package.json
  front/context/src/AccountsContext.tsx
  front/context/src/types.ts
  front/gatsby/gatsby-config.js
  front/gatsby/gatsby-node.js
  front/gatsby/gatsby-ssr.js
  front/gatsby/package.json
  front/gatsby/src/ContextGate.tsx
  front/gatsby/src/components/Layout/Header/Header.module.css
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/components/Layout/Header/index.ts
  front/gatsby/src/components/Layout/Layout.module.css
  front/gatsby/src/components/Layout/Layout.tsx
  front/gatsby/src/components/Layout/index.ts
  front/gatsby/src/components/Seo/Seo.tsx
  front/gatsby/src/components/Seo/index.ts
  front/gatsby/src/components/css.d.ts
  front/gatsby/src/components/image.tsx
  front/gatsby/src/components/index.ts
  front/gatsby/src/components/layout.css
  front/gatsby/src/components/layout.tsx
  front/gatsby/src/components/seo.tsx
  front/gatsby/src/images/gatsby-astronaut.png
  front/gatsby/src/pages/404.tsx
  front/gatsby/src/pages/index.tsx
  front/gatsby/src/pages/onboarding.tsx
  front/gatsby/src/util/constants.ts
  front/gatsby/src/util/index.ts
  front/gatsby/tsconfig.json
  front/ui-components/src/AccountsList.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: A8-looksgood

#138 feat: all server queries and chain header, new session subscription resolvers
  back/node_watcher/kubernetes/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/server/README.md
  back/server/kubernetes/staging/loadbalancer.yaml
  back/server/kubernetes/staging/nomidot-server-staging-namespace.yaml
  back/server/kubernetes/staging/server-deployment.yaml
  back/server/prisma/datamodel.prisma
  back/server/prisma/prisma.yml
  back/server/src/generated/prisma-client/index.ts
  back/server/src/generated/prisma-client/prisma-schema.ts
  back/server/src/index.ts
  back/server/src/resolvers/query.ts
  back/server/src/resolvers/subscription.ts
  back/server/src/schema.graphql
  back/server/src/types.ts
Labels: A7-looksgoodtestsfail

#140 feat: subscription resolvers
  back/node_watcher/kubernetes/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/server/README.md
  back/server/src/resolvers/subscription.ts
  back/server/src/schema.graphql
Labels: A0-pleasereview

#142 fix(context): Also poll on system.health
  front/context/src/SystemContext.tsx
Labels: A8-looksgood

#144 feat: nomidot-server k8s
  back/server/kubernetes/loadbalancer.yaml
  back/server/kubernetes/server-deployment.yaml
  back/server/kubernetes/server-namespace.yaml
  back/server/kubernetes/staging/loadbalancer.yaml
  back/server/kubernetes/staging/server-deployment.yaml
Labels: A0-pleasereview

#147 Update README.md
  README.md
Labels: A2-insubstantial

#145 fix(ui-components): Stateless InputAddress
  front/ui-components/src/InputAddress.tsx
  front/ui-components/src/index.ts
  front/ui-components/src/stateful/index.ts
  front/ui-components/stories/InputAddress.stories.tsx
Labels: A0-pleasereview

#150 fix: referendum statuses not updated
  back/node_watcher/src/tasks/createProposal.ts
  back/node_watcher/src/tasks/createProposalStatus.ts
  back/node_watcher/src/tasks/createReferendum.ts
  back/node_watcher/src/tasks/createReferendumStatus.ts
  back/node_watcher/src/tasks/types.ts
Labels: A0-pleasereview

#152 fix: dont allow package-lock.json into git
  .gitignore
  back/node_watcher/package-lock.json
Labels: A0-pleasereview

#146 feat: apollo client and provider
  back/node_watcher/kubernetes/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  front/gatsby/design-system.d.ts
  front/gatsby/package.json
  front/gatsby/src/apollo.ts
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/pages/index.tsx
  front/gatsby/tsconfig.json
  yarn.lock
Labels: A0-pleasereview

#161 fix: Remove useless stuff from context & ui-components
  front/context/src/TxQueueContext.tsx
  front/context/src/index.ts
  front/context/src/types.ts
  front/context/src/util/index.ts
  front/context/src/util/validate.ts
  front/ui-components/src/InputAddress.tsx
Labels: A8-looksgood

#159 feat(node-watcher): Store motions in chain-db
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/tasks/createMotion.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
  back/node_watcher/src/util/statuses.ts
Labels: A8-looksgood

#158 Readme Nits
  back/node_watcher/README.md
  back/node_watcher/images/2.dockerimagelist.png
Labels: A8-looksgood

#164 feat(node watcher): Add preimage to motions
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/tasks/createMotion.ts
  back/node_watcher/src/tasks/createPreimage.ts
  back/node_watcher/src/tasks/types.ts
  back/node_watcher/src/util/statuses.ts
Labels: A8-looksgood

#162 feat(node-watcher): Write motion status
  back/node_watcher/src/tasks/createMotionStatus.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
Labels: A8-looksgood

#166 feat(node-watcher): Getting the archive node from env
  back/node_watcher/src/nodeWatcher.ts
Labels: A2-insubstantial, A8-looksgood

#167 Fix naming consistency in statuses
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/tasks/createMotion.ts
  back/node_watcher/src/tasks/createMotionStatus.ts
Labels: A0-pleasereview, A2-insubstantial

#157 feat(#141): heartbeats, offline, nominations, rewards, stakes
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/tasks/createHeartbeat.ts
  back/node_watcher/src/tasks/createNominationAndValidators.ts
  back/node_watcher/src/tasks/createOfflineValidator.ts
  back/node_watcher/src/tasks/createReward.ts
  back/node_watcher/src/tasks/createSession.ts
  back/node_watcher/src/tasks/createStake.ts
  back/node_watcher/src/tasks/createTotalIssuance.ts
  back/node_watcher/src/tasks/createValidator.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
  back/node_watcher/src/util/filterEvents.ts
Labels: A8-looksgood

#168 fix(#165): nested query resolvers
  back/server/.graphqlconfig.yml
  back/server/package.json
  back/server/prisma/datamodel.prisma
  back/server/src/generated/prisma-client/index.ts
  back/server/src/generated/prisma-client/prisma-schema.ts
  back/server/src/generated/prisma.graphql
  back/server/src/index.ts
  back/server/src/resolvers/query.ts
  back/server/src/schema.graphql
Labels: A0-pleasereview

#169 feat(#160) - minimize queries
  .eslintrc.js
  back/node_watcher/kubernetes/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/node_watcher/src/nodeWatcher.ts
  back/node_watcher/src/tasks/createBlockNumber.ts
  back/node_watcher/src/tasks/createEra.ts
  back/node_watcher/src/tasks/createHeartbeat.ts
  back/node_watcher/src/tasks/createMotion.ts
  back/node_watcher/src/tasks/createMotionStatus.ts
  back/node_watcher/src/tasks/createNominationAndValidators.ts
  back/node_watcher/src/tasks/createOfflineValidator.ts
  back/node_watcher/src/tasks/createPreimage.ts
  back/node_watcher/src/tasks/createProposal.ts
  back/node_watcher/src/tasks/createProposalStatus.ts
  back/node_watcher/src/tasks/createReferendum.ts
  back/node_watcher/src/tasks/createReferendumStatus.ts
  back/node_watcher/src/tasks/createReward.ts
  back/node_watcher/src/tasks/createSession.ts
  back/node_watcher/src/tasks/createSlashing.ts
  back/node_watcher/src/tasks/createStake.ts
  back/node_watcher/src/tasks/createTotalIssuance.ts
  back/node_watcher/src/tasks/types.ts
Labels: A0-pleasereview

#171 fix: update images
  back/namespaces/prod-namespace.yaml
  back/namespaces/staging-namespace.yaml
  back/node_watcher/kubernetes/namespaces/prod-namespace.yaml
  back/node_watcher/kubernetes/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/server/kubernetes/server-deployment.yaml
Labels: A2-insubstantial

#176 Added types for bn.js. Other docker misc fixes
  back/node_watcher/.dockerignore
  back/node_watcher/Dockerfile
  back/node_watcher/package.json
  back/node_watcher/yarn.lock
Labels: A9-buythatmanabeer

#180 feat (#172): subscription resolvers for stake, heartbeats, offline
  back/server/src/resolvers/subscription.ts
  back/server/src/schema.graphql
Labels: A0-pleasereview, F8-enhancement 🎁

#181 feat(#179): subscribing to heads
  back/server/.dockerignore
  back/server/Dockerfile
  back/server/kubernetes/server-deployment.yaml
  back/server/src/resolvers/subscription.ts
  back/server/yarn.lock
  front/gatsby/src/apollo.ts
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/components/Layout/Header/types.ts
Labels: A0-pleasereview

#156 feat(server): Polkassembly chain-db server
  back/server/prisma/datamodel.prisma
  back/server/src/generated/prisma-client/index.ts
  back/server/src/generated/prisma-client/prisma-schema.ts
  back/server/src/index.ts
  back/server/src/resolvers/query.ts
  back/server/src/resolvers/subscription.ts
  back/server/src/schema.graphql
Labels: A8-looksgood

#182 feat: decoding SCALE hex, query then subscribe, Validators List
  .gitlab-ci.yml
  back/server/kubernetes/loadbalancer.yaml
  back/server/src/resolvers/subscription.ts
  front/gatsby/package.json
  front/gatsby/src/apollo.ts
  front/gatsby/src/components/Layout/Header/Header.module.css
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/components/Layout/Header/types.ts
  front/gatsby/src/components/Layout/Layout.module.css
  front/gatsby/src/components/Layout/Layout.tsx
  front/gatsby/src/components/Layout/Validators/CurrentElected.tsx
  front/gatsby/src/components/Layout/Validators/Validators.tsx
  front/gatsby/src/components/Layout/Validators/index.ts
  front/gatsby/src/components/Layout/Validators/types.ts
  front/gatsby/src/components/Layout/graphql.ts
  front/gatsby/src/pages/index.tsx
  front/gatsby/src/util/createType.ts
  yarn.lock
Labels: A0-pleasereview

#185 Added persistance blockIndex
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/nodeWatcher.ts
  yarn.lock
Labels: A8-looksgood

#194 Fix where args not taken into account
  back/server/src/resolvers/query.ts
Labels: A0-pleasereview

#196 fix(context): Create a new {Api,System}Context on new provider
  front/context/src/ApiContext.tsx
  front/context/src/SystemContext.tsx
Labels: A0-pleasereview

#191 feat: app wide routing setup with @reach/router
  back/server/kubernetes/server-deployment.yaml
  front/context/src/AccountsContext.tsx
  front/gatsby/gatsby-browser.js
  front/gatsby/gatsby-config.js
  front/gatsby/gatsby-node.js
  front/gatsby/package.json
  front/gatsby/src/components/Layout/Header/Header.module.css
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/components/Layout/Layout.module.css
  front/gatsby/src/components/Layout/Layout.tsx
  front/gatsby/src/components/Layout/Validators/index.ts
  front/gatsby/src/images/gatsby-icon.png
  front/gatsby/src/images/polkadot.png
  front/gatsby/src/pages/AccountsList.tsx
  front/gatsby/src/pages/CurrentElected.tsx
  front/gatsby/src/pages/Validators.tsx
  front/gatsby/src/pages/index.tsx
  front/gatsby/src/pages/types.ts
  front/gatsby/src/util/graphql.ts
  yarn.lock
Labels: A0-pleasereview

#202 chore: bump deps
  .eslintrc.js
  back/node_watcher/package.json
  back/node_watcher/src/nodeWatcher.ts
  back/server/package.json
  front/context/package.json
  front/gatsby/package.json
  jest.config.js
  package.json
  yarn.lock
Labels: A5-grumble

#203 fix: js heap out of memory
  back/node_watcher/package.json
Labels: A0-pleasereview

#207 feat: accounts page
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  front/context/src/AccountsContext.tsx
  front/gatsby/gatsby-wrappers.js
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/pages/accounts.tsx
  front/gatsby/src/util/helpers.ts
Labels: A0-pleasereview

#209 fix: redirection and other navigation bugs
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/pages/accounts.tsx
  front/gatsby/src/pages/index.tsx
  front/gatsby/src/pages/validators.tsx
Labels: A0-pleasereview, A2-insubstantial

#183 Added Treasury in chain_db and node_watcher
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/tasks/createMotion.ts
  back/node_watcher/src/tasks/createTreasury.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
  back/node_watcher/src/util/statuses.ts
Labels: A7-looksgoodcantmerge

#193 Track council members
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/tasks/createCouncil.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
  back/server/prisma/datamodel.prisma
  back/server/src/generated/prisma-client/index.ts
  back/server/src/generated/prisma-client/prisma-schema.ts
  back/server/src/generated/prisma.graphql
  back/server/src/index.ts
  back/server/src/resolvers/query.ts
  back/server/src/schema.graphql
Labels: A7-looksgoodcantmerge
