Repository paritytech/Nomidot, pull requests merged in 2020-01, with the labels that each got.

#52 fix: package names and versions
  back/server/package.json
  front/gatsby/package.json
Labels: A2-insubstantial

#49 Deploy Frontend
  back/node_watcher/package.json
  back/node_watcher/src/nodeWatcher.ts
  back/server/.graphqlconfig.yml
  back/server/kubernetes/staging/loadbalancer.yaml
  back/server/kubernetes/staging/server-deployment.yaml
  back/server/package.json
  front/Dockerfile
  front/context/src/AccountsContext.tsx
  front/gatsby/package.json
  front/gatsby/src/pages/home.tsx
  front/gatsby/src/pages/index.tsx
  front/gatsby/src/pages/onboarding.tsx
  front/kubernetes/staging/frontend-deployment.yaml
  front/kubernetes/staging/loadbalancer.yaml
  front/kubernetes/staging/namespace.yaml
  front/scripts/clean-build.sh
  package.json
  yarn.lock
Labels: A0-pleasereview

#54 chore: change script dir location
  scripts/clean-build.sh
  yarn.lock
Labels: bug

#56 fix: make tsc emit properly
  back/node_watcher/package.json
  back/server/package.json
  front/context/package.json
  front/ui-components/package.json
  front/ui-components/src/stateful/Balance.tsx
  tsconfig.json
Labels: bug

#76 chore: Make CI green again
  .eslintignore
  .gitlab-ci.yml
  back/node_watcher/e2e/nomidotSpecVersion1020.spec.ts
  back/node_watcher/src/tasks/createValidator.ts
  back/node_watcher/tsconfig.json
  front/context/src/AccountsContext.tsx
  front/context/src/KeyringContext.tsx
  front/context/src/StakingContext.tsx
  front/gatsby/src/pages/home.tsx
  front/gatsby/src/pages/onboarding.tsx
  front/ui-components/src/BalanceDisplay.tsx
  front/ui-components/src/Fab.tsx
  front/ui-components/src/WalletCard.tsx
  front/ui-components/src/stateful/Balance.tsx
  front/ui-components/src/stateful/InputAddress.tsx
  front/ui-components/stories/BalanceDisplay.stories.tsx
  front/ui-components/stories/InputAddress.stories.tsx
  front/ui-components/stories/customDecorators/index.ts
  front/ui-components/stories/customDecorators/withApi.tsx
  front/ui-components/stories/customDecorators/withKeyring.tsx
  jest.config.js
  package.json
  tsconfig.json
Labels: A0-pleasereview

#81 fix: build and run the transpiled index.js for prod
  back/node_watcher/kubernetes/staging/deployments/nomidotwatcher-deployment.yaml
  back/node_watcher/package.json
Labels: A0-pleasereview

#84 feat: Make ApiContext take a `provider` prop
  front/context/src/ApiContext.tsx
  front/ui-components/package.json
  front/ui-components/stories/customDecorators/withApi.tsx
  package.json
  scripts/clean-build.sh
Labels: A0-pleasereview

#85 chore: Make CI green again, part2
  front/gatsby/src/ContextGate.tsx
  front/ui-components/stories/customDecorators/withApi.tsx
Labels: A0-pleasereview

#86 feat: Create proposal and proposalArguments
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/nodeWatcher.ts
  back/node_watcher/src/tasks/createProposal.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
Labels: A0-pleasereview

#89 Set proposal id as Int
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
Labels: A8-looksgood

#91 docs: Writeup on Nomidot
  CONTRIBUTING.md
  README.md
Labels: A8-looksgood, documentation

#95 Add at(blockNumber, args) to createProposal
  back/node_watcher/src/tasks/createProposal.ts
Labels: A0-pleasereview, A2-insubstantial

#99 fix: docker
  back/node_watcher/Dockerfile
  back/node_watcher/kubernetes/staging/deployments/nomidotwatcher-deployment.yaml
  back/node_watcher/package.json
  back/node_watcher/src/generated/prisma-client/index.ts
Labels: A0-pleasereview

#96 feat: Separate preimage from proposal
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/tasks/createPreimage.ts
  back/node_watcher/src/tasks/createProposal.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
Labels: A8-looksgood

#103 Add Proposal status update
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/tasks/createProposal.ts
  back/node_watcher/src/tasks/createProposalStatus.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
Labels: A0-pleasereview

#104 fix(node-watcher): Override with chain types
  back/node_watcher/package.json
  back/node_watcher/src/nodeWatcher.ts
  package.json
  yarn.lock
Labels: A0-pleasereview

#105 Create Referenda
  back/node_watcher/datamodel.prisma
  back/node_watcher/src/generated/prisma-client/index.ts
  back/node_watcher/src/generated/prisma-client/prisma-schema.ts
  back/node_watcher/src/tasks/createPreimage.ts
  back/node_watcher/src/tasks/createReferendum.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
Labels: A8-looksgood

#107 Create referendum status
  back/node_watcher/src/tasks/createPreimage.ts
  back/node_watcher/src/tasks/createProposal.ts
  back/node_watcher/src/tasks/createProposalStatus.ts
  back/node_watcher/src/tasks/createReferendum.ts
  back/node_watcher/src/tasks/createReferendumStatus.ts
  back/node_watcher/src/tasks/index.ts
  back/node_watcher/src/tasks/types.ts
  back/node_watcher/src/util/statuses.ts
Labels: A0-pleasereview

#110 fix: image and k8 for recent fixes
  back/node_watcher/kubernetes/staging/deployments/nomidotwatcher-deployment.yaml
  back/node_watcher/package.json
Labels: A0-pleasereview

#114 feat(context): Add HealthContext
  front/context/src/HealthContext.tsx
  front/context/src/index.ts
Labels: A7-looksgoodtestsfail

#115 chore: Make nomidot-server a private package
  CHANGELOG.md
  back/node_watcher/CHANGELOG.md
  back/node_watcher/package.json
  back/server/package.json
  front/context/CHANGELOG.md
  front/context/package.json
  front/gatsby/CHANGELOG.md
  front/gatsby/package.json
  front/ui-components/CHANGELOG.md
  front/ui-components/package.json
  package.json
Labels: A2-insubstantial, A8-looksgood

#124 fix(#77): back/server eslint errors
  .eslintignore
  back/node_watcher/e2e/nomidotSpecVersion1020.spec.ts
  back/server/src/index.ts
  back/server/src/utils.ts
  front/gatsby/package.json
  tsconfig.json
Labels: A0-pleasereview
