Repository paritytech/Nomidot, pull requests merged in 2020-04, with the labels that each got.

#278 fix: Use domains instead of ips
  back/node_watcher/kubernetes/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/node_watcher/kubernetes/v1.5/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/v1.5/nomidotwatcher-last-50k-job.yaml
  back/server/kubernetes/server-deployment.yaml
Labels: A0-pleasereview

#280 fix: Add Loadbalancer static ip
  back/server/kubernetes/loadbalancer.yaml
Labels: A8-looksgood

#283 refactor/redesign: navigation
  back/node_watcher/kubernetes/nodewatcher-deployment-staging.yaml
  front/context/src/AccountsContext.tsx
  front/gatsby/package.json
  front/gatsby/src/components/BondingModal.tsx
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/components/Layout/Header/HeaderItem.tsx
  front/gatsby/src/components/Layout/Header/Subheaders/BlockHeader.tsx
  front/gatsby/src/components/Layout/Header/Subheaders/EraHeader.tsx
  front/gatsby/src/components/Layout/Header/Subheaders/SessionHeader.tsx
  front/gatsby/src/components/Layout/Header/Subheaders/StakingHeader.tsx
  front/gatsby/src/components/Layout/Layout.tsx
  front/gatsby/src/components/Layout/Sidebar.tsx
  yarn.lock
Labels: A0-pleasereview

#284 Docker v1.2.31
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/node_watcher/package.json
Labels: A0-pleasereview, A2-insubstantial

#285 feat: cache accounts context results
  front/context/src/AccountsContext.tsx
  front/context/src/util/index.ts
  front/context/src/util/stashes.ts
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/pages/accounts.tsx
  yarn.lock
Labels: A0-pleasereview

#293 Docker image v1.2.32
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/node_watcher/kubernetes/v1.5/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/v1.5/nomidotwatcher-last-50k-job.yaml
  back/node_watcher/package.json
Labels: A0-pleasereview

#291 fix(context): Make provider optional in contexts
  front/context/src/HealthContext.tsx
  front/context/src/SystemContext.tsx
Labels: A0-pleasereview

#290 feat: extension signer
  front/context/src/AccountsContext.tsx
  front/context/src/TxQueueContext.tsx
  front/gatsby/gatsby-wrappers.js
  front/gatsby/package.json
  front/gatsby/src/components/BondingModal.tsx
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/components/Layout/Sidebar.tsx
  front/gatsby/src/components/Status.tsx
  front/gatsby/src/components/index.ts
  yarn.lock
Labels: A0-pleasereview

#295 fix: styling for tables and account page
  front/gatsby/src/components/BondingModal.tsx
  front/gatsby/src/components/Button.tsx
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/components/Layout/Sidebar.tsx
  front/gatsby/src/components/Table.tsx
  front/gatsby/src/components/index.ts
  front/gatsby/src/pages/accounts.tsx
  yarn.lock
Labels: A0-pleasereview

#296 feat: server, node endpionts per env
  front/gatsby/src/apollo.ts
  yarn.lock
Labels: A0-pleasereview

#298 feat: set cpu/mem requests and limits for prisma and cloudsql
  back/node_watcher/kubernetes/nodewatcher-deployment-staging.yaml
  back/server/kubernetes/server-deployment.yaml
Labels: A0-pleasereview

#294 fix(context): Add local-storage dep
  front/context/package.json
  front/gatsby/package.json
Labels: A8-looksgood

#303 fix(context): Reset context parameters when we change provider
  front/context/src/HealthContext.tsx
  front/context/src/SystemContext.tsx
Labels: A0-pleasereview

#305 Docker image v1.2.32 again
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/node_watcher/package.json
Labels: A0-pleasereview

#302 feat: Split ApiContext into ApiPromiseContext and ApiRxContext
  CHANGELOG.md
  front/context/CHANGELOG.md
  front/context/src/AccountsContext.tsx
  front/context/src/ApiContext.tsx
  front/context/src/ApiPromiseContext.tsx
  front/context/src/ApiRxContext.tsx
  front/context/src/index.ts
  front/context/src/types.ts
  front/gatsby/gatsby-wrappers.js
  front/gatsby/src/components/BondingModal.tsx
  front/gatsby/src/components/Cart/CartItems.tsx
  front/gatsby/src/components/Layout/Header/Subheaders/EraHeader.tsx
  front/gatsby/src/components/Layout/Header/Subheaders/StakingHeader.tsx
  front/gatsby/src/pages/accounts.tsx
  front/gatsby/src/pages/validators.tsx
Labels: A0-pleasereview

#308 chore: Bump everywhere to 0.4.0
  CHANGELOG.md
  back/node_watcher/package.json
  front/context/CHANGELOG.md
  front/gatsby/CHANGELOG.md
  front/gatsby/package.json
  lerna.json
Labels: A0-pleasereview

#311 fix(context): Don't instantiate API twice
  front/context/src/ApiPromiseContext.tsx
  front/context/src/ApiRxContext.tsx
  front/context/src/util/index.ts
  front/context/src/util/useEffect.ts
Labels: A0-pleasereview

#323 feat: nodewatcher docker 1.2.33
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/node_watcher/package.json
Labels: A0-pleasereview

#322 Bump api to 1.12.0@beta-10
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
  back/node_watcher/package.json
  back/node_watcher/src/tasks/createPreimage.ts
  front/context/package.json
  package.json
  yarn.lock
Labels: A0-pleasereview

#317 fix: clean up eslint warnings in front/
  back/node_watcher/src/tasks/createPreimage.ts
  front/context/src/AccountsContext.tsx
  front/context/src/TxQueueContext.tsx
  front/gatsby/gatsby-wrappers.js
  front/gatsby/src/components/AccountsDropdown.tsx
  front/gatsby/src/components/BondingModal.tsx
  front/gatsby/src/components/Button.tsx
  front/gatsby/src/components/Layout/Layout.tsx
  front/gatsby/src/components/Layout/Sidebar.tsx
  front/gatsby/src/components/NominationDetails.tsx
  front/gatsby/src/components/StatItem.tsx
  front/gatsby/src/components/Status.tsx
  front/gatsby/src/components/index.ts
  front/gatsby/src/pages/accounts.tsx
  front/gatsby/src/pages/cart.tsx
  yarn.lock
Labels: A0-pleasereview

#326 fix: dont try to write on unique constraint invariant
  back/node_watcher/package.json
  back/node_watcher/src/tasks/createBlockNumber.ts
  back/node_watcher/src/tasks/createSession.ts
  back/node_watcher/src/tasks/types.ts
Labels: A0-pleasereview

#327 feat: extension check
  front/context/src/AccountsContext.tsx
  front/gatsby/src/components/BondingModal.tsx
  front/gatsby/src/components/Button.tsx
  front/gatsby/src/pages/index.tsx
  front/gatsby/src/pages/install.tsx
Labels: A0-pleasereview

#328 fix: remove useless check
  front/context/src/AccountsContext.tsx
  front/gatsby/src/components/NominationDetails.tsx
  front/gatsby/src/pages/cart.tsx
Labels: A0-pleasereview

#336 fix: Add treasury to motions
  back/server/src/index.ts
Labels: A0-pleasereview

#334 chore: update server
  back/server/kubernetes/server-deployment.yaml
  back/server/package.json
  back/server/prisma/datamodel.prisma
  back/server/src/generated/prisma-client/index.ts
  back/server/src/generated/prisma-client/prisma-schema.ts
  back/server/src/generated/prisma.graphql
  back/server/src/index.ts
  back/server/src/resolvers/subscription.ts
  back/server/src/schema.graphql
Labels: A8-looksgood
