Repository paritytech/Nomidot, pull requests merged in 2020-03, with the labels that each got.

#219 Add index to last 50k job
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
Labels: A0-pleasereview

#224 Fix treasury query "at"
  back/node_watcher/src/tasks/createTreasury.ts
Labels: A0-pleasereview

#225 last 50k with new identifier
  back/node_watcher/kubernetes/nomidotwatcher-last-50k-job.yaml
Labels: A0-pleasereview, A2-insubstantial

#229 Add treasury queries to server
  back/server/prisma/datamodel.prisma
  back/server/src/generated/prisma-client/index.ts
  back/server/src/generated/prisma-client/prisma-schema.ts
  back/server/src/generated/prisma.graphql
  back/server/src/index.ts
  back/server/src/resolvers/query.ts
  back/server/src/schema.graphql
Labels: A2-insubstantial, A8-looksgood

#231 Subscription treasury
  back/server/src/resolvers/subscription.ts
  back/server/src/schema.graphql
Labels: A8-looksgood

#232 Server docker image v0.3
  back/server/kubernetes/server-deployment.yaml
Labels: A8-looksgood

#237 Make subscription (with where) work just like prisma server
  back/server/src/generated/prisma-client/index.ts
  back/server/src/index.ts
  back/server/src/resolvers/subscription.ts
  back/server/src/schema.graphql
Labels: A8-looksgood

#241 fix(context): Remove useless keyring from context
  front/context/package.json
  front/context/src/util/keyring.ts
  yarn.lock
Labels: A0-pleasereview

#242 Add max lag
  back/node_watcher/package.json
  back/node_watcher/src/nodeWatcher.ts
  back/node_watcher/src/tasks/index.ts
  package.json
  yarn.lock
Labels: A0-pleasereview

#228 feat: accounts context
  front/context/src/AccountsContext.tsx
  front/context/src/ApiContext.tsx
  front/gatsby/package.json
  front/gatsby/src/components/AccountsDropdown.tsx
  front/gatsby/src/components/Cart/CartItems.tsx
  front/gatsby/src/components/Layout/Header/Header.tsx
  front/gatsby/src/components/NominationDetails.tsx
  front/gatsby/src/pages/accounts.tsx
  front/gatsby/src/pages/index.tsx
  yarn.lock
Labels: A0-pleasereview

#246 fix: replicasets
  back/node_watcher/kubernetes/nodewatcher-deployment-staging.yaml
  back/server/kubernetes/server-deployment.yaml
Labels: A0-pleasereview, D1 - Dev Ops, F8-enhancement 🎁

#251 Support new api for referendumInfo
  back/node_watcher/package.json
  back/node_watcher/src/tasks/createReferendum.ts
  back/node_watcher/src/util/filterEvents.ts
  back/node_watcher/src/util/getReferendumStatus.ts
  package.json
  yarn.lock
Labels: A0-pleasereview

#255 feat: v1.5 sync
  back/node_watcher/kubernetes/v1.5/nodewatcher-deployment-staging.yaml
  back/node_watcher/kubernetes/v1.5/nodewatcher-service.yaml
  back/node_watcher/kubernetes/v1.5/nomidotwatcher-job.yaml
Labels: A0-pleasereview

#262 fix era logging annoyance
  back/node_watcher/kubernetes/fillin-commented-job.yaml
  back/node_watcher/kubernetes/nomidotwatcher-job.yaml
  back/node_watcher/package.json
  back/node_watcher/src/tasks/createEra.ts
Labels: A0-pleasereview, A2-insubstantial

#265 fix: v1.5 sync
  back/node_watcher/kubernetes/fillin-commented-job.yaml
  back/node_watcher/kubernetes/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/v1.5/nomidotwatcher-job.yaml
  back/node_watcher/kubernetes/v1.5/nomidotwatcher-last-50k-job.yaml
  back/node_watcher/package.json
Labels: A0-pleasereview

#256 feat: accounts page
  front/context/src/AccountsContext.tsx
  front/context/src/TxQueueContext.tsx
  front/gatsby/gatsby-wrappers.js
  front/gatsby/src/components/AccountsDropdown.tsx
  front/gatsby/src/components/BondingModal.tsx
  front/gatsby/src/components/Cart/CartItems.tsx
  front/gatsby/src/components/Layout/Header/Subheaders/EraHeader.tsx
  front/gatsby/src/components/Layout/Header/Subheaders/StakingHeader.tsx
  front/gatsby/src/pages/accounts.tsx
  front/gatsby/src/pages/cart.tsx
  front/gatsby/src/pages/index.tsx
  front/gatsby/src/util/cartHelpers.ts
  front/gatsby/src/util/index.ts
  front/gatsby/src/util/stakingHelpers.ts
  front/gatsby/src/util/validateExtrinsic.ts
Labels: A0-pleasereview

#269 feat: new header
  front/gatsby/src/components/Layout/Header/Header.tsx
Labels: A0-pleasereview

#270 fix: server deployment strategy, nodewatcher replicas
  back/node_watcher/kubernetes/nodewatcher-deployment-staging.yaml
  back/server/kubernetes/server-deployment.yaml
Labels: A0-pleasereview, D1 - Dev Ops
